using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OctomodEditor.Models
{
    public enum AttributeResistance { NONE, WEAK, REDUCE, INVALID }
    public enum CharacterRace { UNKNOWN, HUMAN, BEAST, INSECT, BIRD, FISH, DRAGON, PLANT, CHIMERA, SHELL, UNDEAD, DEVIL }
    public enum CharacterSize { SMALL, MEDIUM, LARGE }
    public enum EnemyDeadType { DEADTYPE0, DEADTYPE1, DEADTYPE2, DEADTYPE3, DEADTYPE4, DEADTYPE5 }
    public enum ItemCategory { CONSUMABLE, EQUIPMENT, INFORMATION, MATERIAL_A, MATERIAL_B, TRADING, TREASURE }
    public enum ItemDisplayType { DISABLE, ITEM_USE, ON_HIT, BATTLE_START, ON_TAKE_DAMAGE }
    public enum ItemUseType { DISABLE, ALWAYS, FIELD_ONLY, BATTLE_ONLY }
    public enum TargetType { SELF, PARTY_SINGLE, PARTY_ALL, ENEMY_SINGLE, ENEMY_ALL, ALL, ALL_SINGLE }
    public enum AttributeType { NONE, FIRE, ICE, LIGHTNING, WIND, LIGHT, DARK }
    public enum EquipmentCategory { ACCESSORY, AXE, BEAST, BOW, CLOTH, DAGGER, HAT, HEAVY_ARMOR, HEAVY_HELMET, HUMAN, LANCE, LIGHT_ARMOR, LIGHT_HELMET, PLANT, ROD, SHIELD, SWORD, UNDEAD }
    public enum ShopType { WEAPON, ITEM, GENERAL, INN, BAR }
    public enum AbilityType { PHYSICS, MAGIC, HP_RECOVERY, MP_RECOVERY, REVIVE, TAME_MONSTER, OTHER, BUFF, DEBUFF, REVIVE_RECOVERY }
    public enum AbilityUseType { ALWAYS, BATTLE_ONLY, FIELD_ONLY, SUPPORT }
    public enum WeaponCategory { SWORD, LANCE, DAGGER, AXE, BOW, ROD, NONE }
    public enum AbilityCostType { NONE, MP, HP, MONEY, NUM, BP, SP, MP_RATIO }
    public enum AbilityOrderChangeType { TOP, SECONDLY, ADD_ONE, SUB_ONE, END, NONE }
    public enum SupportAilmentType { MERCHANT_SUPPORT_001, MERCHANT_SUPPORT_002, MERCHANT_SUPPORT_003, MERCHANT_SUPPORT_004, 
                                     THIEF_SUPPORT_001, THIEF_SUPPORT_002, THIEF_SUPPORT_003, THIEF_SUPPORT_004,
                                     FENCER_SUPPORT_001, FENCER_SUPPORT_002, FENCER_SUPPORT_003, FENCER_SUPPORT_004,
                                     HUNTER_SUPPORT_001, HUNTER_SUPPORT_002, HUNTER_SUPPORT_003, HUNTER_SUPPORT_004,
                                     PRIEST_SUPPORT_001, PRIEST_SUPPORT_002, PRIEST_SUPPORT_003, PRIEST_SUPPORT_004,
                                     DANCER_SUPPORT_001, DANCER_SUPPORT_002, DANCER_SUPPORT_003, DANCER_SUPPORT_004,
                                     PROFESSOR_SUPPORT_001, PROFESSOR_SUPPORT_002, PROFESSOR_SUPPORT_003, PROFESSOR_SUPPORT_004,
                                     ALCHEMIST_SUPPORT_001, ALCHEMIST_SUPPORT_002, ALCHEMIST_SUPPORT_003, ALCHEMIST_SUPPORT_004,
                                     WEAPON_MASTER_SUPPORT_001, WEAPON_MASTER_SUPPORT_002, WEAPON_MASTER_SUPPORT_003, WEAPON_MASTER_SUPPORT_004,
                                     WIZARD_SUPPORT_001, WIZARD_SUPPORT_002, WIZARD_SUPPORT_003, WIZARD_SUPPORT_004,
                                     ASTRONOMY_SUPPORT_001, ASTRONOMY_SUPPORT_002, ASTRONOMY_SUPPORT_003, ASTRONOMY_SUPPORT_004,
                                     RUNE_MASTER_SUPPORT_001, RUNE_MASTER_SUPPORT_002, RUNE_MASTER_SUPPORT_003, RUNE_MASTER_SUPPORT_004 }
}
